spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:8ccfa947-3229-47aa-ad60-9ca5a29fbeca;MODE=MySQL

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

